# Pandas

In [20]:
import pandas as pd

## Création DF

In [11]:
pd.DataFrame([1, 2, 42])

0
0   1
1   2
2  42

In [12]:
pd.DataFrame([1, 2, 42], columns = ["number"])

number
0       1
1       2
2      42

In [13]:
# Créer un DF "fruit"
fruit = [[30, 21]]
df = pd.DataFrame(fruit, columns = ["apple", "bananas"])
df

apple  bananas
0     30       21

## Index

In [14]:
data = {"2017 sales" : [35, 21], "2018 sales" : [41, 34]}
x = pd.DataFrame.from_dict(data, orient = "index", columns = ["apples", "bananas"])
x

apples  bananas
2017 sales      35       21
2018 sales      41       34

## Manipulation

### Delete / drop

### Importer un fichier + paramètres

## Afficher

#### Des lignes

#### Types et valeurs de chq colonnes

#### Séléctionner 1ligne ou une colonne : SLICING

### Index

## Maths

## Valeurs nulles/manquantes

## EXEMPLES

## NB

# Numpy

In [1]:
import numpy as np

## Convertir en array (matrice)

In [ ]:
# création
data = [[0,1,2], [10,11,12], [20,21,22], [30,31,32]]
data_np = np.array(data)
data_np

# modification
# ex : 1 ligne et 32 colonnes
array_2 = np.reshape(data_np, (1,32))

## Sélectionner éléments ds tableaux

In [17]:
# élement d'une rangée
print(data_np[1,0 : 2])

# élément d'une colonne
print(data_np[: , 2])

# on sélectionne la ligne à l'indice 0 puis on sélectionne les données des colonnes allant de l'indice  à inclus
print(data_np[0, 3:5])

# lignes aux indices allant de 4 jusqu'à la fin. Puis les colonnes allant de 4 jusqu'à la fin
print(data_np[4: , 4:])

# ttes les lignes puis les colonnes à l'indice 2
print(data_np[:, 2])

# les lignes à partir de l'indice 2, puis une ligne sur 2. Puis on sélectionne les colonnes à partir du début puis 1 colonne sur 2
print(data_np[2::2, ::2])

# si deux matrices
# trouver valeur aux index 1 et colonnes 3 et4
data_np[:,1 , 2:5]  # se lit matrice, ligne, colonne

[10 11]
[ 2 12 22 32]
[]
[]
[ 2 12 22 32]
[[20 22]]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

### Maths sur array

In [22]:
# somme totale
liste = [[12,5], [8,32], [25,6], [7,14]]
data = np.array(liste)
print(data)
print(np.sum(data))

# somme d'une colonne
print(np.sum(data, axis = 0))

# somme d'une rangée
print(np.sum(data, axis =1))

[[12  5]
 [ 8 32]
 [25  6]
 [ 7 14]]
109
[52 57]
[17 40 31 21]


## taille

In [15]:
# taille matrice
print(data_np.shape)

# nb axes
print(data_np.ndim)

(4, 3)
2


# Fonction Apply / Lambda

## Def

## EXEMPLES

# Fonction datetime

In [21]:
from datetime import datetime

In [28]:
# ex
#création d'une variable x dans laquelle je vais convertir un str en date
x = datetime.strptime("2018-01-04", "%Y-%m-%d")
print(x)
#je print le type de ma variable pour confirmer le passage en format date
print(type(x))

2018-01-04 00:00:00
<class 'datetime.datetime'>


# Merge

# Concat

# Pivot table / Cross table

## Synthaxes

## EXEMPLES

# Explode

# Factoriser / get_dummies()

# EXEMPLES